import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../pages/layout/footer.page";
import NavBar from "../pages/layout/header.page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sherpa Travel Partner | Find Yourself a Travel Partner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
